# Generated by Django 5.2.17 on 2026-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0004_dynamic_trigger_found_fix"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="knowledgerelease",
            name="v2_knowledge_release_ck_2",
        ),
        migrations.AddConstraint(
            model_name="knowledgerelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state__in", ["draft", "ready", "blocked"]),
                        ("published_at__isnull", True),
                    ),
                    models.Q(
                        ("state__in", ["published", "retired"]),
                        ("published_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="v2_knowledge_release_ck_2",
            ),
        ),
    ]
