# Generated by Django 5.2.17 on 2026-09-22 16:42

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION adviser_v2_assert_turn_route_binding_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Turn route bindings are immutable';
END;
$$;

CREATE OR REPLACE FUNCTION adviser_v2_assert_turn_route_commitment_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.route_commitment <> ''
       AND NEW.route_commitment IS DISTINCT FROM OLD.route_commitment THEN
        RAISE EXCEPTION 'Turn route commitments are immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER adviser_v2_turn_route_binding_immutable
BEFORE UPDATE OR DELETE ON adviser_v2_turn_route_binding FOR EACH ROW
EXECUTE FUNCTION adviser_v2_assert_turn_route_binding_immutable();

CREATE TRIGGER adviser_v2_turn_route_commitment_immutable
BEFORE UPDATE OF route_commitment ON adviser_v2_turn FOR EACH ROW
EXECUTE FUNCTION adviser_v2_assert_turn_route_commitment_immutable();

"""


REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS adviser_v2_turn_route_commitment_immutable ON adviser_v2_turn;
DROP TRIGGER IF EXISTS adviser_v2_turn_route_binding_immutable
  ON adviser_v2_turn_route_binding;
DROP FUNCTION IF EXISTS adviser_v2_assert_turn_route_commitment_immutable();
DROP FUNCTION IF EXISTS adviser_v2_assert_turn_route_binding_immutable();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("adviser_v2", "0011_three_product_demo_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="route_commitment",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "requested"),
                    ("granted", "granted"),
                    ("revoked", "revoked"),
                ],
                default="requested",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TurnRouteBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("fact_interpretation", "fact_interpretation"),
                            ("recommendation_answer", "recommendation_answer"),
                        ],
                        max_length=24,
                    ),
                ),
                ("requested_model", models.CharField(max_length=160)),
                ("expected_model", models.CharField(max_length=160)),
                ("observed_model", models.CharField(max_length=160)),
                ("endpoint_profile", models.CharField(max_length=120)),
                ("adapter_version", models.CharField(max_length=120)),
                ("route_configuration_sha256", models.CharField(max_length=64)),
                ("schema_sha256", models.CharField(max_length=64)),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turn_bindings",
                        to="adviser_v2.modelqualification",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turn_bindings",
                        to="adviser_v2.modelroute",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_bindings",
                        to="adviser_v2.turn",
                    ),
                ),
            ],
            options={
                "db_table": "adviser_v2_turn_route_binding",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("turn", "role"), name="v2_turn_route_binding_uq_1"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["fact_interpretation", "recommendation_answer"])
                        ),
                        name="v2_turn_route_binding_role_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("route_configuration_sha256__regex", "^[0-9a-f]{64}$")
                        ),
                        name="v2_turn_route_binding_config_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_sha256__regex", "^[0-9a-f]{64}$")),
                        name="v2_turn_route_binding_schema_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expected_model", models.F("observed_model"))),
                        name="v2_turn_route_binding_identity_ck",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("route_commitment", ""),
                    ("route_commitment__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="v2_turn_route_commitment_ck",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
