# Generated by Django 5.2.17 on 2026-10-01 18:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adviser_v2", "0014_three_product_catalogue"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeReleaseFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("validation_sha256", models.CharField(max_length=64)),
                ("criterion", models.CharField(max_length=80)),
                ("fact", models.JSONField()),
                ("fact_sha256", models.CharField(max_length=64)),
                (
                    "knowledge_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.knowledgerelease",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.policyversion",
                    ),
                ),
                (
                    "validation_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.processingjob",
                    ),
                ),
            ],
            options={
                "db_table": "adviser_v2_knowledge_release_fact",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("knowledge_release", "policy_version", "criterion"),
                        name="v2_release_fact_criterion_uq",
                    )
                ],
            },
        ),
    ]
