# Generated by Django 5.2.17 on 2026-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0016_prepared_fact_publication_gates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonstatement",
            name="support_status",
            field=models.CharField(
                choices=[
                    ("supported", "supported"),
                    ("partly_supported", "partly_supported"),
                    ("unsupported", "unsupported"),
                    ("customer_profile_supported", "customer_profile_supported"),
                    ("unknown", "unknown"),
                ],
                default="unverified",
                max_length=26,
            ),
        ),
    ]
