# Generated by Django 5.2.17 on 2026-10-02 12:31

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0017_source_answer_unknown_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoPlanIndex",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("plan_key", models.CharField(max_length=160)),
                ("insurer", models.CharField(max_length=160)),
                ("name", models.CharField(max_length=250)),
                ("variant", models.CharField(default="Default", max_length=120)),
                ("plan_type", models.CharField(default="unresolved", max_length=32)),
                ("uin", models.CharField(blank=True, max_length=100)),
                ("edition", models.CharField(blank=True, max_length=200)),
                ("bundle_path", models.TextField()),
                ("card", models.JSONField(default=dict)),
                ("coverage", models.JSONField(default=dict)),
                ("models_used", models.JSONField(default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("plan_key", "id"), name="demo_plan_version_uq")
                ],
            },
        ),
        migrations.CreateModel(
            name="DemoRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(default="retrieval_demo", max_length=32)),
                (
                    "method",
                    models.CharField(choices=[("H", "H"), ("P", "P")], max_length=1),
                ),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("bakeoff", models.JSONField()),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("indexes", models.ManyToManyField(to="adviser_v2.demoplanindex")),
            ],
        ),
        migrations.CreateModel(
            name="DemoSectionVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                ("text_sha256", models.CharField(max_length=64)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adviser_v2.demoplanindex",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_revision", models.PositiveIntegerField(default=1)),
                ("profile_ciphertext", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_revision", models.PositiveIntegerField()),
                ("erasure_generation", models.PositiveIntegerField()),
                ("input_ciphertext", models.BinaryField()),
                ("state", models.CharField(default="queued", max_length=24)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.demorelease",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adviser_v2.demosession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoPlanAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(default="queued", max_length=24)),
                ("result_ciphertext", models.BinaryField(null=True)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("total_ms", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.demoplanindex",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="adviser_v2.demoquestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "index"), name="demo_plan_answer_uq"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="demorelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("active",),
                name="demo_one_active_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="demosectionvector",
            constraint=models.UniqueConstraint(
                fields=("index", "section_id"), name="demo_section_vector_uq"
            ),
        ),
    ]
