# Generated by Django 5.2.17 on 2026-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adviser_v2", "0018_retrieval_demo_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoquestion",
            name="execution_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="demoquestion",
            name="heartbeat_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
