# Generated by Django 5.2.17 on 2026-10-02 18:46

from django.db import migrations


def isolated_database_only(apps, schema_editor):
    if schema_editor.connection.settings_dict['NAME'] not in {'coverguide_star_slice', 'test_coverguide_star_slice'}:
        raise RuntimeError('Legacy index retirement is restricted to the isolated demo and its test database.')


class Migration(migrations.Migration):

    dependencies = [
        ("adviser_v2", "0019_demo_question_recovery"),
    ]

    operations = [
        migrations.RunPython(isolated_database_only, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="conversationmessagechunk",
            name="v2_conversation_messa_92df564e",
        ),
        migrations.RemoveIndex(
            model_name="policysearchchunk",
            name="v2_policy_search_chunk_ix_2",
        ),
    ]
