# Generated by Django 5.2.17 on 2026-10-03 13:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0020_retire_legacy_hnsw_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_ciphertext", models.BinaryField()),
                ("revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.demorelease",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guided",
                        to="adviser_v2.demosession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemoChatTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("base_revision", models.PositiveIntegerField()),
                ("input_ciphertext", models.BinaryField()),
                ("output_ciphertext", models.BinaryField()),
                ("elapsed_ms", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="adviser_v2.democonversation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "request_id"),
                        name="demo_chat_idempotency_uq",
                    )
                ],
            },
        ),
    ]
