# Generated by Django 5.2.17 on 2026-10-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adviser_v2", "0021_guided_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoFactCard",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("card", models.JSONField()),
                ("audit_path", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.demoplanindex",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="demorelease",
            name="fact_cards",
            field=models.ManyToManyField(blank=True, to="adviser_v2.demofactcard"),
        ),
    ]
