# Generated by Django 5.2.17 on 2026-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0023_fact_card_immutability"),
    ]

    operations = [
        migrations.AddField(
            model_name="democonversation",
            name="title_ciphertext",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="democonversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
