# Generated by Django 5.2.17 on 2026-10-07 16:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser_v2", "0024_conversation_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoquestion",
            name="profile_bound",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="DemoTopicAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=40)),
                ("method", models.CharField(max_length=1)),
                ("status", models.CharField(max_length=24)),
                ("validator", models.CharField(max_length=80)),
                ("draft", models.CharField(max_length=80)),
                ("result_ciphertext", models.BinaryField()),
                ("model", models.CharField(blank=True, max_length=80)),
                ("total_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser_v2.demoplanindex",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index", "topic", "method"), name="demo_topic_answer_uq"
                    )
                ],
            },
        ),
    ]
