services:
  redis:
    image: redis:7.2-alpine@sha256:ccd6aa8d45ff3f033d6fa15b8cc1a50579f65c89f38cf9bb607a954c4f2128ed
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6401:6379"
    volumes:
      - star_slice_redis:/data
    restart: unless-stopped

volumes:
  star_slice_redis:
