import { expect, test } from "@playwright/test";

test("user selects a qualified model, asks a cited policy question, and reviews interview details", async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto("/");
  await page.getByRole("button", { name: "New here? Create an account" }).click();
  await page.getByRole("textbox", { name: "Email" }).fill(`ai-e2e-${Date.now()}@example.com`);
  await page.getByRole("textbox", { name: "Password" }).fill("E2E-Valid-Password-42");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByRole("button", { name: "AI settings", exact: true }).click();
  const models = page.getByRole("combobox", { name: "Your AI model", exact: true });
  await expect(models).toBeEnabled();
  await expect(models.locator("option")).toHaveCount(4);
  await expect(models.locator("option:checked")).toHaveText("gpt-6-astra");
  await expect(page.getByText("Codex subscription", { exact: true })).toHaveCount(0);
  await models.selectOption({ label: "gpt-5.6-sol" });
  await expect(page.getByRole("status")).toContainText("saved");
  await page.reload();
  await page.getByRole("button", { name: "AI settings", exact: true }).click();
  await expect(models.locator("option:checked")).toHaveText("gpt-5.6-sol");
  await models.selectOption({ label: "gpt-6-astra" });
  await expect(page.getByRole("status")).toContainText("saved");
  await page.getByRole("button", { name: "＋ New conversation" }).click();
  const message = page.getByRole("textbox", { name: "Ask a policy question or tell me about your needs…" });
  await message.fill("What is the pre-existing disease waiting period in Care Supreme?");
  await page.getByRole("button", { name: "Send →" }).click();
  await expect(page.getByText(/36-month waiting period/)).toBeVisible({ timeout: 110_000 });
  await page.getByRole("button", { name: "Open source 1" }).first().click();
  await expect(page.getByRole("complementary", { name: "Citation source" })).toBeVisible();
  await expect.poll(() => page.locator(".pdf-page canvas").evaluate((element) => (element as HTMLCanvasElement).width)).toBeGreaterThan(0);
  await page.getByRole("button", { name: "Close source" }).click();
  await page.reload();
  await expect(page.getByText(/36-month waiting period/)).toBeVisible();
  await message.fill("I live in Bengaluru.");
  await page.getByRole("button", { name: "Send →" }).click();
  await expect(page.getByRole("button", { name: "Add these details to my profile" })).toBeVisible({ timeout: 110_000 });
  await page.getByRole("button", { name: "Add these details to my profile" }).click();
  await expect(page.getByRole("textbox", { name: "Location", exact: true })).toHaveValue(/Bengaluru/);
  await expect(page.getByText(/Revision 2/)).toBeVisible();
});

test("pilot admin sees the shared account and qualification controls", async ({ browser }) => {
  test.skip(!process.env.COVERGUIDE_PILOT_STATE, "Requires a temporary local pilot session.");
  const context = await browser.newContext({ storageState: process.env.COVERGUIDE_PILOT_STATE });
  const page = await context.newPage();
  await page.goto("/");
  await page.getByRole("button", { name: "AI settings", exact: true }).click();
  await expect(page.getByText("Laptop-wide connection", { exact: true })).toBeVisible();
  await expect(page.getByText("Connected", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Switch Codex account" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Test and qualify", exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/ai-settings-admin.png", fullPage: true });
  await context.close();
});
