# Generated by Django 5.2.17 on 2026-09-09 11:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("manifest", models.JSONField(default=dict)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("physical_index", models.PositiveIntegerField()),
                ("printed_label", models.CharField(blank=True, max_length=30)),
                ("width", models.DecimalField(decimal_places=4, max_digits=12)),
                ("height", models.DecimalField(decimal_places=4, max_digits=12)),
                ("rotation", models.SmallIntegerField(default=0)),
                ("geometry", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_type", models.CharField(max_length=100)),
                ("language", models.CharField(default="en", max_length=20)),
                ("identity", models.CharField(max_length=300)),
                ("effective_from", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Insurer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("aliases", models.JSONField(default=list)),
                ("official_domains", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("stored_path", models.CharField(max_length=500, unique=True)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceLocator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(max_length=1000)),
                ("source_organisation", models.CharField(max_length=250)),
                ("expected_document_type", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="New conversation", max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnswerArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("outcome", models.CharField(max_length=40)),
                ("blocks", models.JSONField(default=list)),
                ("verification_status", models.CharField(max_length=30)),
                ("profile_revision", models.PositiveIntegerField(null=True)),
                (
                    "corpus_release",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.corpusrelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnswerClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claim_type", models.CharField(max_length=40)),
                ("display_text", models.TextField()),
                ("fact_ids", models.JSONField(default=list)),
                ("verification_result", models.CharField(max_length=30)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="adviser.answerartifact",
                    ),
                ),
                (
                    "evidence_bundles",
                    models.ManyToManyField(to="adviser.evidencebundle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceSpan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("region_id", models.CharField(max_length=100)),
                ("start_line", models.PositiveIntegerField()),
                ("end_line", models.PositiveIntegerField()),
                ("source_word_ids", models.JSONField(default=list)),
                ("quote", models.TextField()),
                ("geometry", models.JSONField(default=list)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.documentpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundleSpan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="primary", max_length=30)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adviser.evidencebundle",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.evidencespan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="spans",
            field=models.ManyToManyField(
                through="adviser.EvidenceBundleSpan", to="adviser.evidencespan"
            ),
        ),
        migrations.CreateModel(
            name="ExtractionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revision", models.PositiveIntegerField()),
                ("parser_manifest", models.JSONField(default=dict)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("source_map_path", models.CharField(max_length=500)),
                ("published", models.BooleanField(default=False)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.documentversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentpage",
            name="extraction_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="adviser.extractionrevision",
            ),
        ),
        migrations.CreateModel(
            name="CatalogueListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ditto_path", models.CharField(max_length=500, unique=True)),
                ("displayed_name", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("downloaded", "Downloaded"),
                            ("parsed", "Parsed"),
                            ("awaiting_review", "Awaiting Review"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="discovered",
                        max_length=30,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                ("last_observed_at", models.DateTimeField()),
                (
                    "insurer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.insurer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("origin", models.CharField(default="text", max_length=30)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="adviser.conversation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uin", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=250)),
                ("variant", models.CharField(blank=True, max_length=200)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("available_for_new_purchase", models.BooleanField(null=True)),
                ("review_state", models.CharField(default="pending", max_length=30)),
                (
                    "insurer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.insurer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanDocumentAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(max_length=100)),
                ("applicability", models.JSONField(default=dict)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.documentversion",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.planversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revision", models.PositiveIntegerField()),
                ("data", models.JSONField(default=dict)),
                ("field_provenance", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="adviser.conversation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="current_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for",
                to="adviser.profilerevision",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile_revision", models.PositiveIntegerField()),
                ("candidate_results", models.JSONField(default=list)),
                ("rankings", models.JSONField(default=list)),
                ("calculations", models.JSONField(default=list)),
                ("rule_version", models.CharField(max_length=50)),
                (
                    "answer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.answerartifact",
                    ),
                ),
                (
                    "corpus_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.corpusrelease",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="documentversion",
            name="blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="adviser.sourceblob"
            ),
        ),
        migrations.CreateModel(
            name="SourceObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fetched_at", models.DateTimeField()),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("available", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                (
                    "locator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.sourcelocator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("input_text", models.TextField()),
                ("operation", models.CharField(default="chat", max_length=50)),
                ("expected_profile_revision", models.PositiveIntegerField(null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="adviser.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TurnAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("needs_input", "Needs Input"),
                            ("insufficient_evidence", "Insufficient Evidence"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("superseded", "Superseded"),
                        ],
                        default="accepted",
                        max_length=30,
                    ),
                ),
                ("profile_revision", models.PositiveIntegerField(null=True)),
                ("deadline_at", models.DateTimeField()),
                ("terminal_code", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corpus_release",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.corpusrelease",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="adviser.turn",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answerartifact",
            name="attempt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answer",
                to="adviser.turnattempt",
            ),
        ),
        migrations.CreateModel(
            name="VerifiedFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=100)),
                ("value_type", models.CharField(max_length=30)),
                ("value", models.JSONField()),
                ("applicability", models.JSONField(default=dict)),
                (
                    "verification_state",
                    models.CharField(default="pending", max_length=30),
                ),
                ("conflict", models.BooleanField(default=False)),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.evidencebundle",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.planversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="evidencebundlespan",
            constraint=models.UniqueConstraint(
                fields=("bundle", "span"), name="unique_bundle_span"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrevision",
            constraint=models.UniqueConstraint(
                fields=("document_version", "revision"),
                name="unique_extraction_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(
                fields=("extraction_revision", "physical_index"),
                name="unique_extraction_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("insurer", "uin", "variant", "effective_from"),
                name="unique_plan_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandocumentassociation",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "document_version", "role"),
                name="unique_plan_document_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilerevision",
            constraint=models.UniqueConstraint(
                fields=("conversation", "revision"), name="unique_profile_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("conversation", "request_id"), name="unique_turn_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="turnattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["accepted", "running"])),
                fields=("turn",),
                name="one_active_attempt_per_turn",
            ),
        ),
    ]
