# Generated by Django 5.2.17 on 2026-09-09 12:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0002_enable_vector_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stage", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=30)),
                ("inputs", models.JSONField(default=dict)),
                ("outputs", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("relay_type", models.CharField(max_length=40)),
                ("base_url", models.URLField(max_length=1000)),
                ("configured_model", models.CharField(max_length=200)),
                ("api_dialect", models.CharField(max_length=50)),
                ("capabilities", models.JSONField(default=dict)),
                ("context_limit", models.PositiveIntegerField()),
                ("timeout_policy", models.JSONField(default=dict)),
                ("configuration_hash", models.CharField(max_length=64, unique=True)),
                (
                    "qualification_state",
                    models.CharField(default="unqualified", max_length=30),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="review_state",
            field=models.CharField(default="pending", max_length=30),
        ),
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("section_path", models.JSONField(default=list)),
                ("heading", models.CharField(blank=True, max_length=500)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.documentversion",
                    ),
                ),
                (
                    "evidence_bundles",
                    models.ManyToManyField(to="adviser.evidencebundle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PremiumObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("assumptions", models.JSONField(default=dict)),
                ("tax_basis", models.CharField(blank=True, max_length=100)),
                ("observed_at", models.DateTimeField()),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.evidencebundle",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.planversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RatingObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rating", models.DecimalField(decimal_places=3, max_digits=6)),
                ("scale", models.DecimalField(decimal_places=3, max_digits=6)),
                ("observed_at", models.DateTimeField()),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.evidencebundle",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.planversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("expected_revision", models.CharField(max_length=100)),
                ("decision", models.CharField(max_length=30)),
                ("reason", models.TextField()),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModelCallAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.CharField(max_length=50)),
                ("requested_model", models.CharField(max_length=200)),
                (
                    "upstream_reported_model",
                    models.CharField(blank=True, max_length=200),
                ),
                ("status", models.CharField(max_length=30)),
                ("duration_ms", models.PositiveIntegerField(null=True)),
                ("reported_usage", models.JSONField(default=dict)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                (
                    "turn_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adviser.turnattempt",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.routeconfiguration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RouteQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tested_configuration_hash", models.CharField(max_length=64)),
                ("evaluation_results", models.JSONField(default=dict)),
                ("state", models.CharField(max_length=30)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.routeconfiguration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
