# Generated by Django 5.2.17 on 2026-09-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0003_ingestionrun_routeconfiguration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerartifact",
            name="attempt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="adviser.turnattempt",
            ),
        ),
        migrations.AlterField(
            model_name="recommendationsnapshot",
            name="answer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adviser.answerartifact",
            ),
        ),
    ]
