# Generated by Django 5.2.17 on 2026-09-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0004_alter_answerartifact_attempt_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="planversion",
            name="unique_plan_identity",
        ),
        migrations.AddField(
            model_name="conversation",
            name="active_attempt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_conversation",
                to="adviser.turnattempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("insurer", "uin", "variant", "effective_from"),
                name="unique_plan_identity",
                nulls_distinct=False,
            ),
        ),
    ]
