# Generated by Django 5.2.17 on 2026-09-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0006_attempt_conversation_invariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="answer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message",
                to="adviser.answerartifact",
            ),
        ),
    ]
