# Generated by Django 5.2.17 on 2026-09-09 14:23

from django.db import migrations, models


def select_latest_active_release(apps, schema_editor):
    CorpusRelease = apps.get_model("adviser", "CorpusRelease")
    latest = (
        CorpusRelease.objects.filter(activated_at__isnull=False).order_by("-activated_at").first()
    )
    if latest is not None:
        CorpusRelease.objects.filter(pk=latest.pk).update(is_current=True)


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0007_link_messages_to_answers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidencebundlespan",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="corpusrelease",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(select_latest_active_release, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="corpusrelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="one_current_corpus_release",
            ),
        ),
    ]
