# Generated by Django 5.2.17 on 2026-09-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("adviser", "0008_current_corpus_and_evidence_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="adviser.routeconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="turnattempt",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="adviser.routeconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="modelcallattempt",
            name="turn_attempt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adviser.turnattempt",
            ),
        ),
        migrations.CreateModel(
            name="AIPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adviser.routeconfiguration",
                    ),
                ),
            ],
        ),
    ]
