# Generated by Django 5.2.17 on 2026-09-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="erasure_generation",
            field=models.BigIntegerField(default=0),
        ),
    ]
